spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: loan-service
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
  datasource:
    url: jdbc:postgresql://localhost:5432/eatup
    username: postgres
    password: sa
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      hbm2ddl:
        auto: update
      ejb:
        naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true
      default_schema: dental
  liquibase:
    changelog: classpath:/db/db.changelog-master.xml
    enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8088
